python training_clean_data_3f.py --device 1 --model 3f_model_fold1_clean_huge --train_data fold_1_train_10cv --val_data fold_1_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold2_clean_huge --train_data fold_2_train_10cv --val_data fold_2_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold3_clean_huge --train_data fold_3_train_10cv --val_data fold_3_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold4_clean_huge --train_data fold_4_train_10cv --val_data fold_4_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

python training_clean_data_3f.py --device 1 --model 3f_model_fold1_clean_large --train_data fold_1_train_10cv --val_data fold_1_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold2_clean_large --train_data fold_2_train_10cv --val_data fold_2_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold3_clean_large --train_data fold_3_train_10cv --val_data fold_3_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold4_clean_large --train_data fold_4_train_10cv --val_data fold_4_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

python training_clean_data_3f.py --device 1 --model 3f_model_fold1_clean --train_data fold_1_train_10cv --val_data fold_1_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold2_clean --train_data fold_2_train_10cv --val_data fold_2_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold3_clean --train_data fold_3_train_10cv --val_data fold_3_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 1 --model 3f_model_fold4_clean --train_data fold_4_train_10cv --val_data fold_4_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
