python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold5_clean_huge --train_data fold_5_train_10cv --val_data fold_5_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold6_clean_huge --train_data fold_6_train_10cv --val_data fold_6_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold7_clean_huge --train_data fold_7_train_10cv --val_data fold_7_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold5_clean_large --train_data fold_5_train_10cv --val_data fold_5_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold6_clean_large --train_data fold_6_train_10cv --val_data fold_6_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold7_clean_large --train_data fold_7_train_10cv --val_data fold_7_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold5_clean --train_data fold_5_train_10cv --val_data fold_5_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold6_clean --train_data fold_6_train_10cv --val_data fold_6_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold7_clean --train_data fold_7_train_10cv --val_data fold_7_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
