#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_mixup_training --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_bn --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_mixup_training --use_batch_norm --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou_bn --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou_bn_adam --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.5
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou_bn_hard --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.75 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou_bn_hard2 --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.75 --optimizer sgd --load_model model_fold2_clean_iou_bn_hard
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou_ce_small --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_ce_loss --use_batch_norm --dropout 0.75 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_iou_ce_tiny --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_ce_loss --use_batch_norm --dropout 0.4 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold2_clean_ce_tiny_mixup --train_data fold_2_train --val_data fold_2_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_ce_loss --use_batch_norm --dropout 0.4 --use_mixup_training --optimizer sgd

python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold8_clean --train_data fold_8_train_10cv --val_data fold_8_val_10cv --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_ce_loss --use_batch_norm --do_not_exclude --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold9_clean --train_data fold_9_train_10cv --val_data fold_9_val_10cv --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_ce_loss --use_batch_norm --do_not_exclude --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold10_clean --train_data fold_10_train_10cv --val_data fold_10_val_10cv --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_ce_loss --use_batch_norm --do_not_exclude --dropout 0.75 --optimizer sgd --record_best_model

#python inference_clean_preds.py --device 0 --memory_limit 0.495 --load_model model_fold2_clean_iou_ce_tiny --data_to_infer fold_2_train --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 0 --memory_limit 0.495 --load_model model_fold2_clean_iou_ce_tiny --data_to_infer fold_2_val --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 0 --memory_limit 0.495 --load_model model_fold2_clean_iou_ce_small --data_to_infer fold_2_train --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 0 --memory_limit 0.495 --load_model model_fold2_clean_iou_ce_small --data_to_infer fold_2_val --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 0 --memory_limit 0.495 --load_model model_fold2_clean_iou_bn_hard2 --data_to_infer fold_2_train --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 0 --memory_limit 0.495 --load_model model_fold2_clean_iou_bn_hard2 --data_to_infer fold_2_val --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_batch_norm