python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold8_clean_huge --train_data fold_8_train_10cv --val_data fold_8_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold9_clean_huge --train_data fold_9_train_10cv --val_data fold_9_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold10_clean_huge --train_data fold_10_train_10cv --val_data fold_10_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold8_clean_large --train_data fold_8_train_10cv --val_data fold_8_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold9_clean_large --train_data fold_9_train_10cv --val_data fold_9_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold10_clean_large --train_data fold_10_train_10cv --val_data fold_10_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold8_clean --train_data fold_8_train_10cv --val_data fold_8_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold9_clean --train_data fold_9_train_10cv --val_data fold_9_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model
python training_clean_data_3f.py --device 0 --memory_limit 0.495 --model 3f_model_fold10_clean --train_data fold_10_train_10cv --val_data fold_10_val_10cv --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_decay_schedule --use_batch_norm --dropout 0.75 --optimizer sgd --record_best_model

