#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold3_clean --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_mixup_training --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold3_clean_iou --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold3_clean_bn --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_mixup_training --use_batch_norm --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold3_clean_iou_bn --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.5 --optimizer sgd
#python training_clean_data.py --device 0 --memory_limit 0.495 --model model_fold3_clean_iou_bn_adam --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.5
#python training_clean_data.py --device 1 --model model_fold3_clean_iou_bn_hard --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.75 --optimizer sgd
#python training_clean_data.py --device 1 --model model_fold3_clean_iou_bn_hard2 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_iou_loss --use_batch_norm --dropout 0.75 --optimizer sgd --load_model model_fold3_clean_iou_bn_hard
#python training_clean_data.py --device 1 --model model_fold3_clean_iou_ce_small --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_ce_loss --use_batch_norm --dropout 0.75 --optimizer sgd
#python training_clean_data.py --device 1 --model model_fold3_clean_iou_ce_tiny --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_ce_loss --use_batch_norm --dropout 0.4 --optimizer sgd

#python inference_clean_preds.py --device 1 --load_model model_fold3_clean_iou_ce_tiny --data_to_infer fold_3_train --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 1 --load_model model_fold3_clean_iou_ce_tiny --data_to_infer fold_3_val --hidden_channels 8 --hidden_blocks 4 6 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 1 --load_model model_fold3_clean_iou_ce_small --data_to_infer fold_3_train --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_batch_norm
#python inference_clean_preds.py --device 1 --load_model model_fold3_clean_iou_ce_small --data_to_infer fold_3_val --hidden_channels 8 --hidden_blocks 4 6 8 8 --squeeze_excitation --use_batch_norm
python inference_clean_preds.py --device 1 --load_model model_fold3_clean_iou_bn_hard2 --data_to_infer fold_3_train --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_batch_norm
python inference_clean_preds.py --device 1 --load_model model_fold3_clean_iou_bn_hard2 --data_to_infer fold_3_val --hidden_channels 8 --hidden_blocks 4 6 8 12 8 --squeeze_excitation --use_batch_norm
