python training_event_resnet.py --epochs 35 --device 1 --model model_fold3_event_random_decay --train_data fold_3_train --val_data fold_3_val --num_extra_steps 4 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --squeeze_excitation --use_batch_norm --dropout 0.75 --random_shift 2160 --weight_decay 0.01
python training_event_resnet.py --epochs 35 --device 1 --model model_fold3_event_random_decay_deep --train_data fold_3_train --val_data fold_3_val --num_extra_steps 4 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --squeeze_excitation --use_batch_norm --dropout 0.75 --random_shift 2160 --weight_decay 0.01 --use_deep_supervision 9600000

python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_11 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --kernel_size 11 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01
python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_9 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --kernel_size 9 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01
python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_7 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --kernel_size 7 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01
python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_5 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --kernel_size 5 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01
python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_3 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 4 4 4 4 4 4 --kernel_size 3 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01

python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_3_3 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 3 3 3 3 3 3 --kernel_size 3 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01
python training_clean_data_3f.py --device 1 --model 3f_3cv_all_model_fold3_clean_3_2 --train_data fold_3_train --val_data fold_3_val --num_extra_steps 9 --hidden_channels 2 --hidden_blocks 2 2 2 2 2 2 --kernel_size 3 --squeeze_excitation --do_not_exclude --use_batch_norm --use_deep_supervision --dropout 0.75 --optimizer adam --weight_decay 0.01

python training_event_resnet.py --epochs 35 --device 1 --model model_fold3_event_highdecay_deep --train_data fold_3_train --val_data fold_3_val --num_extra_steps 4 --hidden_channels 2 --hidden_blocks 2 2 2 2 2 2 --kernel_size 3 --squeeze_excitation --use_batch_norm --dropout 0.75 --dropout_pos_embeddings --random_shift 2160 --weight_decay 0.05 --use_deep_supervision 9600000
python training_event_resnet.py --epochs 35 --device 1 --model model_fold3_event_highdecay_deep_sgd --train_data fold_3_train --val_data fold_3_val --num_extra_steps 4 --hidden_channels 2 --hidden_blocks 2 2 2 2 2 2 --kernel_size 3 --squeeze_excitation --use_batch_norm --dropout 0.75 --dropout_pos_embeddings --random_shift 2160 --weight_decay 0.05 --use_deep_supervision 9600000 --optimizer sgd
